name: "CI"

on:
  push:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format-and-lint:
    uses: ./.github/workflows/format-and-lint.yml
    secrets: inherit

  build:
    needs:
      - format-and-lint
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    needs:
      - format-and-lint
    uses: ./.github/workflows/test.yml
    secrets: inherit

  dependencies-check:
    needs:
      - format-and-lint
      - build
      - test
    uses: ./.github/workflows/dependencies-check.yml
    secrets: inherit
