name: "Security & Vulnerability scanning"

on:
  workflow_call:

jobs:
  cargo-udeps:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          override: true

      # The following does not work due to `aig787/cargo-udeps-action@v1` not respecting `working-directory`

      # - uses: aig787/cargo-udeps-action@v1
      #   with:
      #     version: "latest"
      #     args: "--all-targets"

      - uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: cargo-binaries-${{ runner.os }}
          restore-keys: cargo-binaries-

      - run: |
          if ! command -v cargo-udeps >/dev/null; then
            cargo install cargo-udeps --locked
          fi

      - run: cargo udeps --all-targets

  cargo-deny:
    needs:
      - cargo-udeps

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - stable
        check:
          # - advisories
          # - bans licenses sources
          - bans
          - sources

    # Prevent sudden announcement of a new advisory from failing CI:
    continue-on-error: ${{ matrix.check == 'advisories' }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.check }}

  cargo-audit:
    needs:
      - cargo-udeps
      - cargo-deny

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - run: cargo audit
